### ISSUE TITLE
Stage inside line

### ISSUE THREAD

**Issue by yaskevich** [dracor-org/rusdracor#4]
Currently, in several files I've got `stage` within `p`
```xml
<sp who="#neschastlivtsev">
<speaker>Несчастливцев.</speaker>
<p>О, люди, люди! <stage>(Идет в угол, надевает котомку.)</stage></p>
<stage>Аксюша помогает ему и целует его. Берет в руки палку.</stage>
<p>Ну, Аркадий, мы с тобой попировали, пошумели, братец; теперь опять за работу!
<stage>(Выходит на середину сцены, подзывает Карпа и говорит ему с расстановкой и
внушительно.)</stage> Послушай, Карп! Если приедет тройка, ты вороти ее, братец, в
город; скажи, что господа пешком пошли. Руку, товарищ! <stage>(Подает руку
Счастливцеву и медленно удаляется.)</stage></p>
</sp>
```
Maybe, it should be:
```xml
<sp who="#neschastlivtsev">
	<speaker>Несчастливцев.</speaker>
	<p>О, люди, люди!</p>
	<stage>(Идет в угол, надевает котомку.)</stage>			
	<stage>Аксюша помогает ему и целует его. Берет в руки палку.</stage>
	<p>Ну, Аркадий, мы с тобой попировали, пошумели, братец; теперь опять за работу!</p>
	<stage>(Выходит на середину сцены, подзывает Карпа и говорит ему с расстановкой и внушительно.)</stage>
	<p>Послушай, Карп! Если приедет тройка, ты вороти ее, братец, в город; скажи, что господа пешком пошли. Руку, товарищ!</p>
	<stage>(Подает руку Счастливцеву и медленно удаляется.)</stage>
</sp>
```
As to me, the second variant seems better. Or are there different types of `stage`?
(The quotations are from `ostrovsky-les.xml`.)

**Comment by lehkost** [comment]
Exact positions of stage directions are a bit muddy. In your example, the [original from lib.ru](http://az.lib.ru/o/ostrowskij_a_n/text_0130.shtml) reads:

____
**Несчастливцев.** О, люди, люди! *(Идет в угол, надевает котомку.)*

<p align="center"><i>Аксюша помогает ему и целует его. Берет в руки палку.</i></p>

____

What we usually do in these cases for a clean and consistent transformation is that we keep all ```<stage>``` within ```<p>``` if they are in the same line, and separate them if they are in a separate line. This, I would say, is a clear rule, which tries to preserve the original state. But I'm up for discussions as to how else we could handle these cases, as long as it is consistent.

**Comment by yaskevich** [comment]
Now I understand logic, I agree it makes sense.
Actually, what I don't like is that in the cases like this we got XML nodes which are everywhere else are common text nodes, but here they are text nodes **and** container nodes. It breaks semantic difference between content node and container node. And It's not ok for parsing.
```xml
<p>Слышу-с. <stage>(В сторону.)</stage> С радостию ухожу. <stage>(Уходит.)</stage></p>
```
If one extracts text content of `p`, `stage` becomes serialized automatically. It's not easy to iterate children of such nodes by means of XML mechanics.
```xml
<p>Il ne faut pas s'y frotter.<note place="foot">Не нужно здесь толочься (фр.).</note>
              <stage>(Прячется.)</stage></p>
```
The example from the same play, `note` is annotated in the same way, as we discuss `stage`. So, e.g., if we need to understand to what content is related the note, I even cannot tell straight how to easily do it.

*Source: `dashkova-toisiokov.xml`*

**Comment by lehkost** [comment]
Good point! But according to the TEI guidelines, ```<stage>``` might very well be contained by ```<p>``` (see [here](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-stage.html)).
And our extraction routines for speaker text within ```<p>``` and ```<l>``` will exclude ```<stage>``` and ```<note>```, but will include ```<emph>```.

**Comment by yaskevich** [comment]
As to me, TEI is not ideal, and this point is a flaw.
But as soon as it's accordant with TEI, I guess it would be reasonable to discuss it only if we refuse of TEI.
