### ISSUE TITLE
dot in the end of speaker's name

### ISSUE THREAD

**Issue by yaskevich** [dracor-org/rusdracor#6]
Cases like this
```xml
<speaker>Г. Тоисиоков.</speaker>
```
I guess that the dot is presented in the publication, but it's only a part of formatting. If a play is printed with speaker's name separated from speech with indent, we don't find the dot (e.g. `krylov-filomela.xml`).
As soon it's not a part of the content and not needed for presentation, it's not really needed in XML.

It's very low priority question :-)

**Comment by lehkost** [comment]
I understand the preference for unified data 😊, but we should not intervene with the shape of the texts as we find them, including their formatting of speaker names. We're not making a (digital) edition, we "just" convert digitised texts to XML-TEI to be able to do research on them. So, if there are dots in the original printed source, we should copy them over. If not, we don't. The only thing where we *might* intervene is when a printed source is inconsistent itself and omits a dot where it should feature one.

We could, of course, omit dots after speaker names in HTML outputs we generate from our TEI files, but we should leave that to the presentation layer.

**Comment by yaskevich** [comment]
I see the point, completely agree.
Sure, it's not a problem to omit dot in presentation for better readability.

**Comment by agricolamz** [comment]
In `gogol-revizor.xml` the name inside <speaker> tags are even sometimes in genitive case (here is [an example](https://github.com/dracor-org/rusdracor/blob/master/tei/gogol-revizor.xml#L4900)). May be it is possible to add unified form as an atribute to `<speaker>` tag?
