### ISSUE TITLE
new lines inside text

### ISSUE THREAD

**Issue by yaskevich** [dracor-org/rusdracor#7]
For some reason, there are files where inside text lines we have new line characters, like this
```xml
<title type="main" xml:lang="ru">Театральный разъезд после представления новой
          комедии</title>
```
*Source: `gogol-teatralnyi-razezd.xml`*

Of course, it's not important for XML, but if one would like to quickly process bunch of xml files with RegExp or something like this, it would be problem.

And, as to XML, as soon it's not semantics and not presentation, it's not needed.
I can fix this. The issue was created only to discuss the policy.

**Comment by lehkost** [comment]
Absolutely, thanks for bringing this up. I repaired "Театральный разъезд" (https://github.com/dracor-org/rusdracor/commit/56415ea676e9479221513222b97ec8be4535d7a9), feel free to skim through the whole corpus to detect unwanted new line characters.

**Comment by yaskevich** [comment]
It seems that you actually didn't fix new lines, but what you do you repaired the thing
```bash
н CYRILLIC SMALL LETTER EN
ы CYRILLIC SMALL LETTER YERU
и CYRILLIC SMALL LETTER I
̆  COMBINING BREVE
SPACE
р CYRILLIC SMALL LETTER ER
а CYRILLIC SMALL LETTER A
з CYRILLIC SMALL LETTER ZE
```
which a bit tried to drive me crazy, when I tried to extract text according to reg exp for Russian alphabet. 
GH-8 is a fix for couple of new lines in the file.
It's not he end, later I'll check all the files for this issue.

**Comment by lehkost** [comment]
Ah, I see. We should probably search for other ``` ̆  COMBINING BREVE``` and throw them out if we find any.

As for new lines, this is normal. I accepted the pull request, but since we decided to do a line wrap at column 80 in the preferences of our XML editor, it will happen again. As you say, it does not matter in XML, and we haven't really run into a problem with this before.
